# Generated by Django 2.2.3 on 2019-07-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
